openapi: 3.0.0
info:
  title: MELD Visualizer API
  version: 1.0.0
  description: |
    3D visualization platform for MELD manufacturing process data.

servers:
  - url: http://127.0.0.1:8050
    description: Local development server

paths:
  /_dash-update-component:
    post:
      summary: Update Dash component
      description: Internal endpoint for Dash component updates.
      tags:
        - Internal

  /upload/csv:
    post:
      summary: Upload CSV data file
      description: Upload a CSV file containing MELD manufacturing data.
      tags:
        - Data Upload

  /upload/gcode:
    post:
      summary: Upload G-code file
      description: Upload a G-code (.nc) file for toolpath visualization.
      tags:
        - Data Upload

  /config:
    get:
      summary: Get current configuration
      description: Retrieve the current application configuration.
      tags:
        - Configuration

    put:
      summary: Update configuration
      description: Update application configuration settings.
      tags:
        - Configuration
