name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      issues: read
      id-token: write
      actions: read # Required for Claude to read CI results on PRs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          
          # Optional: Specify model (defaults to Claude Sonnet 4, uncomment for Claude Opus 4.1)
          # model: "claude-opus-4-1-20250805"
          
          # Optional: Customize the trigger phrase (default: @claude)
          # trigger_phrase: "/claude"
          
          # Optional: Trigger when specific user is assigned to an issue
          # assignee_trigger: "claude-bot"
          
          # Allow Claude to run project-specific commands
          allowed_tools: |
            Bash(python -m src.meld_visualizer.app)
            Bash(meld-visualizer)
            Bash(pytest*)
            Bash(bash scripts/run_tests.sh*)
            Bash(pip install*)
            Bash(python -m pip install*)
            Bash(pip install -e*)
            Bash(pyinstaller*)
            Bash(python -c*)
            Bash(black*)
            Bash(isort*)
            Bash(ruff*)
          
          # Custom instructions for the MELD Visualizer project
          custom_instructions: |
            This is a Dash web application for visualizing 3D MELD manufacturing data with a modern package structure.
            
            Package Structure:
            - Source code is in src/meld_visualizer/
            - Configuration is in config/config.json
            - Sample data is in data/csv/ and data/nc/
            - Tests are in tests/ with pytest.ini config
            - Scripts are in scripts/
            
            Key project requirements:
            - Follow the modular MVC architecture (src/meld_visualizer/app.py → core/layout.py → callbacks/ → core/data_processing.py)
            - Use existing patterns for Dash callbacks with pattern matching IDs
            - Maintain compatibility with the current theme system (20+ Bootstrap themes)
            - Install as editable package: `pip install -e ".[dev]"`
            - Run tests with pytest: `pytest -m "not e2e"` for unit tests
            - Check that new code works with the existing CSV data processing pipeline
            - Preserve the G-code visualization and volume mesh generation functionality
            - Maintain Python 3.8+ compatibility (see pyproject.toml)
            
            Before making changes:
            1. Install the package in development mode: `pip install -e ".[dev]"`
            2. Run the test suite to ensure existing functionality: `pytest`
            3. Check config/config.json structure if modifying configuration
            4. Test with sample data files in the data/csv/ directory
            5. Use proper imports: `from src.meld_visualizer.core import data_processing`
          
          # Optional: Custom environment variables for Claude
          # claude_env: |
          #   NODE_ENV: test

